# Generated by Django 4.2 on 2026-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.JSONField(default=list, verbose_name='图片列表'),
        ),
        migrations.AddField(
            model_name='post',
            name='moderation_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.JSONField(default=list, verbose_name='话题标签'),
        ),
    ]
